CREATE TABLE IF NOT EXISTS "user" (
    "id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "email" VARCHAR(255),
    "password"  VARCHAR(255),
    "role" VARCHAR(255) ,
    PRIMARY KEY("id")
);


CREATE TABLE IF NOT EXISTS "product_price" (
   "product_id" BIGINT NOT NULL,
   "check_date" DATE NOT NULL,
   "price" DECIMAL,
   PRIMARY KEY("product_id", "check_date")
);


CREATE TABLE IF NOT EXISTS "user_products" (
   "user_id" BIGINT NOT NULL,
   "product_id" BIGINT NOT NULL,
   "notify" BOOLEAN ,
   "thresholdPrice" DECIMAL ,
   PRIMARY KEY("user_id", "product_id")
);

CREATE TYPE marketplace_enum AS ENUM ('wildberries');

CREATE TABLE IF NOT EXISTS "product" (
    "product_id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "marketplace"  marketplace_enum ,
    "url" VARCHAR(255) ,
    "article" BIGINT ,
    "is_tracked" BOOLEAN ,
    "option_name" VARCHAR(255) ,
    "option_id" BIGINT ,
    "name" VARCHAR(255) ,
    "brand" VARCHAR(255) ,
    "image" VARCHAR(255) ,
    PRIMARY KEY("product_id")
);


CREATE VIEW "product_view" AS
SELECT
    product_id AS id,
    marketplace,
    article,
    url,
    option_id
FROM "product";


CREATE TYPE notification_service_type AS ENUM ('telegram', 'vk');

CREATE TABLE IF NOT EXISTS "user_notification" (
   "user_id" BIGINT NOT NULL,
   "notification_service" notification_service_type NOT NULL,
   "external_id" BIGINT,
   PRIMARY KEY("user_id", "notification_service")
);



ALTER TABLE "user_products"
    ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "product_price"
    ADD FOREIGN KEY("product_id") REFERENCES "product"("product_id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user_products"
    ADD FOREIGN KEY("product_id") REFERENCES "product"("product_id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user_notification"
    ADD FOREIGN KEY("user_id") REFERENCES "user"("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
