version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pricehunter-db
    restart: always
    environment:
      POSTGRES_DB: price_hunter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
