server:
  port: 8081

spring:
  application:
    name: integration-service

  kafka:
    bootstrap-servers: broker:9092
    #bootstrap-servers: localhost:9092




external:
  provider:
    wildberries:
      token: ${WB_ACCESS_TOKEN}
      dest: -5817683
      userAgent: ${WB_USER_AGENT}