spring:
  application:
    name: integration-service
  kafka:
    bootstrap-servers: localhost:9092
  config:
    import: optional:file:.env

server:
  port: 8081



external:
  provider:
    wildberries:
      token: ${WB_ACCESS_TOKEN}
      dest: -5817683
      userAgent: ${WB_USER_AGENT}